
name: auto_merge

on:
  workflow_dispatch:
  schedule:
    - cron: 10 * * * *


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true
        token: ${{ secrets.PAT}}

    - name: Set git identity
      run : |
        git config --global user.email "qwq233@qwq2333.top"
        git config --global user.name "github-actions[bot]"
    - name: Load upstream commits
      run:
        git pull https://github.com/ferredoxin/QNotified.git master --ff

        git push -f

